version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/squad-whitelister:default

    command: sleep infinity

    network_mode: service:db

    environment:
      - MONGODB_CONNECTION_STRING=mongodb://root:toor@db:27017/Whitelister?authSource=admin

  db:
    image: mongo:latest
    restart: unless-stopped

    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    environment:
      MONGO_INITDB_DATABASE: Whitelister
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor

volumes:
  mongodb-data:
